name: React Demo Workflow
on: 
  push:
    branches:
      - main
      - 'feature/*'
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    types: [opened, edited]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-code-demo
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
            node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-code-demo
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
            node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
